package com.infernooverlay;

import java.util.HashMap;
import java.util.Map;

/**
 * Static wave composition data for the Inferno (which monster types spawn on each wave).
 * This is reference information only - it does not track or predict anything live.
 */
final class InfernoWaveMappings
{
	static final int NIBBLER = 32;
	static final int BAT = 85;
	static final int BLOB = 165;
	static final int MELEE = 240;
	static final int RANGER = 370;
	static final int MAGE = 490;
	static final int JAD = 900;
	static final int ZUK = 1400;

	static final Map<Integer, int[]> WAVE_MAPPING = new HashMap<>();
	static final Map<Integer, String> SIMPLE_NAMES = new HashMap<>();
	static final Map<Integer, String> COMPLEX_NAMES = new HashMap<>();

	static
	{
		WAVE_MAPPING.put(1, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT});
		WAVE_MAPPING.put(2, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT});
		WAVE_MAPPING.put(3, new int[]{NIBBLER, NIBBLER, NIBBLER, NIBBLER, NIBBLER, NIBBLER});
		WAVE_MAPPING.put(4, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB});
		WAVE_MAPPING.put(5, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BLOB});
		WAVE_MAPPING.put(6, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, BLOB});
		WAVE_MAPPING.put(7, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, BLOB});
		WAVE_MAPPING.put(8, new int[]{NIBBLER, NIBBLER, NIBBLER, NIBBLER, NIBBLER, NIBBLER});
		WAVE_MAPPING.put(9, new int[]{NIBBLER, NIBBLER, NIBBLER, MELEE});
		WAVE_MAPPING.put(10, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, MELEE});
		WAVE_MAPPING.put(11, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, MELEE});
		WAVE_MAPPING.put(12, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, MELEE});
		WAVE_MAPPING.put(13, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BLOB, MELEE});
		WAVE_MAPPING.put(14, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, BLOB, MELEE});
		WAVE_MAPPING.put(15, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, BLOB, MELEE});
		WAVE_MAPPING.put(16, new int[]{NIBBLER, NIBBLER, NIBBLER, MELEE, MELEE});
		WAVE_MAPPING.put(17, new int[]{NIBBLER, NIBBLER, NIBBLER, NIBBLER, NIBBLER, NIBBLER});
		WAVE_MAPPING.put(18, new int[]{NIBBLER, NIBBLER, NIBBLER, RANGER});
		WAVE_MAPPING.put(19, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, RANGER});
		WAVE_MAPPING.put(20, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, RANGER});
		WAVE_MAPPING.put(21, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, RANGER});
		WAVE_MAPPING.put(22, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BLOB, RANGER});
		WAVE_MAPPING.put(23, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, BLOB, RANGER});
		WAVE_MAPPING.put(24, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, BLOB, RANGER});
		WAVE_MAPPING.put(25, new int[]{NIBBLER, NIBBLER, NIBBLER, MELEE, RANGER});
		WAVE_MAPPING.put(26, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, MELEE, RANGER});
		WAVE_MAPPING.put(27, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, MELEE, RANGER});
		WAVE_MAPPING.put(28, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, MELEE, RANGER});
		WAVE_MAPPING.put(29, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BLOB, MELEE, RANGER});
		WAVE_MAPPING.put(30, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, BLOB, MELEE, RANGER});
		WAVE_MAPPING.put(31, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, BLOB, MELEE, RANGER});
		WAVE_MAPPING.put(32, new int[]{NIBBLER, NIBBLER, NIBBLER, MELEE, MELEE, RANGER});
		WAVE_MAPPING.put(33, new int[]{NIBBLER, NIBBLER, NIBBLER, RANGER, RANGER});
		WAVE_MAPPING.put(34, new int[]{NIBBLER, NIBBLER, NIBBLER, NIBBLER, NIBBLER, NIBBLER});
		WAVE_MAPPING.put(35, new int[]{NIBBLER, NIBBLER, NIBBLER, MAGE});
		WAVE_MAPPING.put(36, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, MAGE});
		WAVE_MAPPING.put(37, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, MAGE});
		WAVE_MAPPING.put(38, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, MAGE});
		WAVE_MAPPING.put(39, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BLOB, MAGE});
		WAVE_MAPPING.put(40, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, BLOB, MAGE});
		WAVE_MAPPING.put(41, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, BLOB, MAGE});
		WAVE_MAPPING.put(42, new int[]{NIBBLER, NIBBLER, NIBBLER, MELEE, MAGE});
		WAVE_MAPPING.put(43, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, MELEE, MAGE});
		WAVE_MAPPING.put(44, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, MELEE, MAGE});
		WAVE_MAPPING.put(45, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, MELEE, MAGE});
		WAVE_MAPPING.put(46, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BLOB, MELEE, MAGE});
		WAVE_MAPPING.put(47, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, BLOB, MELEE, MAGE});
		WAVE_MAPPING.put(48, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, BLOB, MELEE, MAGE});
		WAVE_MAPPING.put(49, new int[]{NIBBLER, NIBBLER, NIBBLER, MELEE, MELEE, MAGE});
		WAVE_MAPPING.put(50, new int[]{NIBBLER, NIBBLER, NIBBLER, RANGER, MAGE});
		WAVE_MAPPING.put(51, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, RANGER, MAGE});
		WAVE_MAPPING.put(52, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, RANGER, MAGE});
		WAVE_MAPPING.put(53, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, RANGER, MAGE});
		WAVE_MAPPING.put(54, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BLOB, RANGER, MAGE});
		WAVE_MAPPING.put(55, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, BLOB, RANGER, MAGE});
		WAVE_MAPPING.put(56, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, BLOB, RANGER, MAGE});
		WAVE_MAPPING.put(57, new int[]{NIBBLER, NIBBLER, NIBBLER, MELEE, RANGER, MAGE});
		WAVE_MAPPING.put(58, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, MELEE, RANGER, MAGE});
		WAVE_MAPPING.put(59, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, MELEE, RANGER, MAGE});
		WAVE_MAPPING.put(60, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, MELEE, RANGER, MAGE});
		WAVE_MAPPING.put(61, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BLOB, MELEE, RANGER, MAGE});
		WAVE_MAPPING.put(62, new int[]{NIBBLER, NIBBLER, NIBBLER, BAT, BAT, BLOB, MELEE, RANGER, MAGE});
		WAVE_MAPPING.put(63, new int[]{NIBBLER, NIBBLER, NIBBLER, BLOB, BLOB, MELEE, RANGER, MAGE});
		WAVE_MAPPING.put(64, new int[]{NIBBLER, NIBBLER, NIBBLER, MELEE, MELEE, RANGER, MAGE});
		WAVE_MAPPING.put(65, new int[]{NIBBLER, NIBBLER, NIBBLER, RANGER, RANGER, MAGE});
		WAVE_MAPPING.put(66, new int[]{NIBBLER, NIBBLER, NIBBLER, MAGE, MAGE});
		WAVE_MAPPING.put(67, new int[]{JAD});
		WAVE_MAPPING.put(68, new int[]{JAD, JAD, JAD});
		WAVE_MAPPING.put(69, new int[]{ZUK});

		SIMPLE_NAMES.put(NIBBLER, "Nibbler");
		SIMPLE_NAMES.put(BAT, "Bat");
		SIMPLE_NAMES.put(BLOB, "Blob");
		SIMPLE_NAMES.put(MELEE, "Meleer");
		SIMPLE_NAMES.put(RANGER, "Ranger");
		SIMPLE_NAMES.put(MAGE, "Mage");
		SIMPLE_NAMES.put(JAD, "Jad");
		SIMPLE_NAMES.put(ZUK, "Zuk");

		COMPLEX_NAMES.put(NIBBLER, "Jal-Nib");
		COMPLEX_NAMES.put(BAT, "Jal-MejRah");
		COMPLEX_NAMES.put(BLOB, "Jal-Ak");
		COMPLEX_NAMES.put(MELEE, "Jal-ImKot");
		COMPLEX_NAMES.put(RANGER, "Jal-Xil");
		COMPLEX_NAMES.put(MAGE, "Jal-Zek");
		COMPLEX_NAMES.put(JAD, "JalTok-Jad");
		COMPLEX_NAMES.put(ZUK, "TzKal-Zuk");
	}

	private InfernoWaveMappings()
	{
	}
}
